// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0fNHTO-FW2IzyeFaPLvbtQw2KQeAUe6c',
    appId: '1:1008085104375:web:40218fd4b7df62fdfb85f2',
    messagingSenderId: '1008085104375',
    projectId: 'alert-dev-60d76',
    authDomain: 'alert-dev-60d76.firebaseapp.com',
    storageBucket: 'alert-dev-60d76.appspot.com',
    measurementId: 'G-6151QETDH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2Nk_VKA1YW3BYQnILWV0SgieN-eQwA2c',
    appId: '1:1008085104375:android:115d0e581a0d4cfafb85f2',
    messagingSenderId: '1008085104375',
    projectId: 'alert-dev-60d76',
    storageBucket: 'alert-dev-60d76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkj7Y_U7x5vDzqHjTxZPNGIEkpCBOB3t4',
    appId: '1:1008085104375:ios:9d9d7d766ab8a786fb85f2',
    messagingSenderId: '1008085104375',
    projectId: 'alert-dev-60d76',
    storageBucket: 'alert-dev-60d76.appspot.com',
    iosBundleId: 'com.example.alert',
  );

}